CREATE TABLE skills(
 skill_id int AUTO_INCREMENT NOT NULL PRIMARY KEY,
 skill_type int NOT NULL,
 skill_name VARCHAR(64) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);