CREATE TABLE skills(
 skill_id SERIAL NOT NULL PRIMARY KEY,
 skill_type INTEGER NOT NULL,
 skill_name VARCHAR(64) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);