INSERT INTO skills (skill_type, skill_name) VALUES (1, 'Java');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'JavaScript');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'PLSQL');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'SQL');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'Python');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'PHP');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'Kotlin');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'jQuary');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'CSS');
INSERT INTO skills (skill_type, skill_name) VALUES (1, 'HTML');
INSERT INTO skills (skill_type, skill_name) VALUES (2, 'Linux');
INSERT INTO skills (skill_type, skill_name) VALUES (2, 'Android');
INSERT INTO skills (skill_type, skill_name) VALUES (2, 'Windows');
INSERT INTO skills (skill_type, skill_name) VALUES (3, 'MySQL');
INSERT INTO skills (skill_type, skill_name) VALUES (3, 'PostgreSQL');
INSERT INTO skills (skill_type, skill_name) VALUES (3, 'Oracle');
INSERT INTO skills (skill_type, skill_name) VALUES (4, 'seasar2');
INSERT INTO skills (skill_type, skill_name) VALUES (4, 'Laravel');
INSERT INTO skills (skill_type, skill_name) VALUES (4, 'Spring boot');
INSERT INTO skills (skill_type, skill_name) VALUES (4, 'Vue.js');
INSERT INTO skills (skill_type, skill_name) VALUES (4, 'Angular');
INSERT INTO skills (skill_type, skill_name) VALUES (5, 'AWS');
INSERT INTO skills (skill_type, skill_name) VALUES (5, 'Docker');
INSERT INTO skills (skill_type, skill_name) VALUES (5, 'Apache Tomcat');
INSERT INTO skills (skill_type, skill_name) VALUES (5, 'GitHub');
INSERT INTO skills (skill_type, skill_name) VALUES (5, 'Git');
